version: '3.7'
services:
    db:
        image: mysql:5.7
        volumes:
            - $PWD/data:/var/lib/mysql
        container_name: mysql-magento
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: magento2
            MYSQL_USER: magentoroot
            MYSQL_PASSWORD: magento123
        networks:
            - net-magento
    php:  
        build:
           context: .
           dockerfile: Dockerfile
        container_name: web-magento
        ports:
            - "8080:80"
        networks:
            - net-magento              
networks:
        net-magento:
