version: '3.7'
services:
    db:
        image: mysql:5.7
        volumes:
            - $PWD/data:/var/lib/mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: magento2
            MYSQL_USER: magentoroot
            MYSQL_PASSWORD: magento123
    server:
        image: gonzalodkr/magento2-server:1.2
        container_name: magento
        volumes:
            - $PWD/config:/usr/local/etc/php
