version: '3.7'
services:
    db:
        image: mysql:5.7
        volumes:
            - $PWD/data:/var/lib/mysql
        container_name: dev-mysql-magento
        #ports:
        #    - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: magento2
            MYSQL_USER: magentoroot
            MYSQL_PASSWORD: magento123
        #networks:
            #- beta-magento
    php:  
        build: 
            context: .
            # dockerfile: Dockerfile
        image: magento-beta:2.0
        container_name: dev-web-magento
        ports:
                - "8081:80"
       #networks:
              # - beta-magento           
#networks:
        # beta-magento:
